name: Flutter Test, Build, and Release apk

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Test, Build, and Release new apk
    runs-on: ubuntu-latest

    steps:
      - name: Use Java 11 for build
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.3"
          channel: "stable"

      - name: Get flutter dependencies
        run: flutter pub get

      - name: Flutter Test
        run: flutter test

      - name: Build Android APK
        run: flutter build apk --release

      - name: Rename APK
        run: mv build/app/outputs/apk/release/app-release.apk build/app/outputs/apk/release/ObjectPix.apk

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Automatically generated release for build ${{ github.run_number }}

      - name: Upload APK
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/app/outputs/flutter-apk/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
